
var WAVE_FREQUENCY = 0.12;
var WAVE_AMPLITUDE = 0.50;
var TARGET_WAVE_FREQUENCY = 0.12;
var TARGET_WAVE_AMPLITUDE = 0.50;
var WAVE_INTERPOLATOR = d3.interpolateNumber(WAVE_FREQUENCY, TARGET_WAVE_FREQUENCY);
var WAVE_AMP_INTERPOLATOR = d3.interpolateNumber(WAVE_AMPLITUDE, TARGET_WAVE_AMPLITUDE);
var WAVE_INTERPOLATION = 1.0;
var WAVE_AMP_INTERPOLATION = 1.0;
function GET_WAVE_FREQUENCY() {
	return WAVE_INTERPOLATOR(Math.min(WAVE_INTERPOLATION, 1.0));
}
function GET_WAVE_AMPLITUDE() {
	return WAVE_AMP_INTERPOLATOR(Math.min(WAVE_AMP_INTERPOLATION, 1.0));
}
function updateSpeed(freq) {
	WAVE_FREQUENCY = GET_WAVE_FREQUENCY();
	TARGET_WAVE_FREQUENCY = freq / 100;
	WAVE_INTERPOLATION = 0.0;
	WAVE_INTERPOLATOR = d3.interpolateNumber(WAVE_FREQUENCY, TARGET_WAVE_FREQUENCY);
}
function updateAmount(amp) {
	WAVE_AMPLITUDE = GET_WAVE_AMPLITUDE();
	TARGET_WAVE_AMPLITUDE = amp / 100;
	WAVE_AMP_INTERPOLATION = 0.0;
	WAVE_AMP_INTERPOLATOR = d3.interpolateNumber(WAVE_AMPLITUDE, TARGET_WAVE_AMPLITUDE);
}
